# Generated by Django 2.1.7 on 2019-06-28 05:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='catagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='customer_id')),
                ('password', models.CharField(max_length=50, verbose_name='password')),
                ('nickname', models.CharField(max_length=50, verbose_name='nickname')),
                ('address', models.CharField(max_length=100, verbose_name='address')),
                ('phone_number', models.DecimalField(decimal_places=10, max_digits=11, verbose_name='phone_number')),
            ],
        ),
        migrations.CreateModel(
            name='img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URL', models.URLField(verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='order_id')),
                ('create_time', models.TimeField(verbose_name='create_time')),
                ('payment_time', models.TimeField(verbose_name='payment_time')),
                ('confirm_time', models.TimeField(verbose_name='confirm_time')),
            ],
        ),
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('SKU_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='SKU_id')),
                ('price', models.IntegerField(verbose_name='price')),
                ('amount', models.IntegerField(verbose_name='amount')),
                ('catagorys', models.ManyToManyField(to='main.catagory')),
                ('spec', models.ManyToManyField(to='main.option')),
            ],
        ),
        migrations.CreateModel(
            name='speification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='SPU',
            fields=[
                ('SPU_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='SPU_id')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('SKUs', models.ManyToManyField(to='main.SKU')),
                ('imgs', models.ManyToManyField(to='main.img')),
            ],
        ),
        migrations.CreateModel(
            name='store',
            fields=[
                ('store_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='store_id')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('SPUs', models.ManyToManyField(to='main.SPU')),
            ],
        ),
    ]
