# Generated by Django 2.1.7 on 2019-07-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='password',
        ),
        migrations.AddField(
            model_name='customer',
            name='openid',
            field=models.CharField(default='', max_length=100, verbose_name='openid'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='img',
            name='URL',
            field=models.CharField(max_length=200, verbose_name='URL'),
        ),
    ]
