# Generated by Django 2.1.7 on 2019-06-28 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190628_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sku',
            name='catagorys',
        ),
        migrations.AddField(
            model_name='spu',
            name='catagorys',
            field=models.ManyToManyField(to='main.catagory'),
        ),
    ]
