# Generated by Django 2.1.7 on 2019-07-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190711_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='confirm_time',
            field=models.DateTimeField(verbose_name='confirm_time'),
        ),
        migrations.AlterField(
            model_name='order',
            name='create_time',
            field=models.DateTimeField(verbose_name='create_time'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_time',
            field=models.DateTimeField(verbose_name='payment_time'),
        ),
    ]
