# Generated by Django 2.1.7 on 2019-07-10 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190711_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='snap_address',
            field=models.TextField(default='', verbose_name='snap_address'),
            preserve_default=False,
        ),
    ]
